name: claspenv
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - alsa-lib=1.2.14
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.7.14
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - contourpy=1.3.2
  - cpython=3.10.18
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - cython=3.1.2
  - dbus=1.16.2
  - double-conversion=3.3.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.58.5
  - freetype=2.13.3
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - h5py=3.14.0
  - harfbuzz=11.2.1
  - hdf5=1.14.6
  - icu=75.1
  - jinja2=3.1.6
  - joblib=1.5.1
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libaec=1.1.4
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.8
  - libclang13=20.1.8
  - libcups=2.3.3
  - libcurl=8.14.1
  - libdeflate=1.24
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm20=20.1.8
  - liblzma=5.8.1
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.5
  - libsqlite=3.50.2
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.10.0
  - libxml2=2.13.8
  - libxslt=1.1.39
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - markupsafe=3.0.2
  - matplotlib=3.10.3
  - matplotlib-base=3.10.3
  - mkl=2024.2.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.5
  - networkx=3.4.2
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openssl=3.5.1
  - packaging=25.0
  - pandas=2.3.1
  - patsy=1.0.1
  - pcre2=10.45
  - pillow=11.3.0
  - pip=25.1.1
  - pixman=0.46.2
  - pthread-stubs=0.4
  - pyparsing=3.2.3
  - pyside6=6.9.1
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - qhull=2020.2
  - qt6-main=6.9.1
  - readline=8.2
  - scikit-learn=1.7.0
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - six=1.17.0
  - statsmodels=0.14.5
  - tbb=2021.13.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tornado=6.5.1
  - tzdata=2025b
  - unicodedata2=16.0.0
  - wayland=1.24.0
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.45
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - zstd=1.5.7
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - appdirs==1.4.4
      - async-timeout==5.0.1
      - attrs==25.3.0
      - beautifulsoup4==4.13.4
      - biopandas==0.5.1
      - biopython==1.85
      - bioservices==1.12.1
      - cattrs==25.1.1
      - certifi==2025.7.14
      - charset-normalizer==3.4.2
      - click==8.2.1
      - git+https://github.com/openai/CLIP.git
      - colorama==0.4.6
      - colorlog==6.9.0
      - cpdb-protein==0.2.0
      - deepdiff==8.5.0
      - easydev==0.13.3
      - exceptiongroup==1.3.0
      - filelock==3.18.0
      - frozenlist==1.7.0
      - fsspec==2025.7.0
      - ftfy==6.3.1
      - gevent==25.5.1
      - graphein==1.7.7
      - greenlet==3.2.3
      - grequests==0.7.0
      - hf-xet==1.1.5
      - huggingface-hub==0.33.4
      - idna==3.10
      - iniconfig==2.1.0
      - jaxtyping==0.3.2
      - line-profiler==4.2.0
      - loguru==0.7.3
      - looseversion==1.1.2
      - lxml==5.4.0
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - mmtf-python==1.1.3
      - msgpack==1.1.1
      - multidict==6.6.3
      - multipledispatch==1.0.0
      - narwhals==1.47.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - orderly-set==5.5.0
      - pexpect==4.9.0
      - platformdirs==4.3.8
      - plotly==6.2.0
      - pluggy==1.6.0
      - propcache==0.3.2
      - protobuf==6.31.1
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - pytest==8.4.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.4
      - requests-cache==1.2.1
      - rich==14.0.0
      - rich-click==1.8.9
      - sacremoses==0.1.1
      - safetensors==0.5.3
      - setuptools==80.9.0
      - soupsieve==2.7
      - suds-community==1.2.0
      - sympy==1.13.1
      - tokenizers==0.21.2
      - tomli==2.2.1
      - torch==2.6.0
      - torch-geometric==2.6.1
      - tqdm==4.67.1
      - transformers==4.53.2
      - triton==3.2.0
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - url-normalize==2.2.1
      - urllib3==2.5.0
      - wadler-lindig==0.1.7
      - wcwidth==0.2.13
      - wget==3.2
      - wrapt==1.17.2
      - xarray==2025.6.1
      - xmltodict==0.14.2
      - yarl==1.20.1
      - zope-event==5.1
      - zope-interface==7.2
